// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "UBC UAS",
            "url": "https://ubcuas.com/",
            "email": "info@ubcuas.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/status": {
            "get": {
                "description": "Get the current status of the drone",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drone"
                ],
                "summary": "Get drone status",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/models.Drone"
                        }
                    }
                }
            }
        },
        "/status/history": {
            "get": {
                "description": "Get drone status for the last 5 minutes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drone"
                ],
                "summary": "Get drone status history",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Drone"
                            }
                        }
                    }
                }
            }
        },
        "/waypoint": {
            "post": {
                "description": "Create a singular waypoint based on JSON, must have sentinel ID of \"-1\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Waypoint"
                ],
                "summary": "Create a waypoint",
                "parameters": [
                    {
                        "description": "Waypoint data.",
                        "name": "waypoint",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Waypoint"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/responses.WaypointResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Waypoint Data",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Error Creating Waypoint",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/waypoint/{id}": {
            "get": {
                "description": "Get a singular waypoint based on path param",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Waypoint"
                ],
                "summary": "Get a waypoint",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Waypoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/responses.WaypointResponse"
                        }
                    },
                    "404": {
                        "description": "Waypoint Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Error Querying Waypoint",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a singular waypoint based on path param",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Waypoint"
                ],
                "summary": "Delete a waypoint",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Waypoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success (returns a blank Waypoint)",
                        "schema": {
                            "$ref": "#/definitions/responses.WaypointResponse"
                        }
                    },
                    "404": {
                        "description": "Waypoint Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Error Deleting Waypoint",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Edit a singular waypoint based on path param and JSON",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Waypoint"
                ],
                "summary": "Edit a waypoint",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Waypoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "example": "{\"name\": \"Whiskey}",
                        "description": "JSON fields",
                        "name": "fields",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/responses.WaypointResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Waypoint ID",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Waypoint Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Error Editing Waypoint",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/waypoints": {
            "get": {
                "description": "Get all waypoints in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Waypoint"
                ],
                "summary": "Get all waypoints",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/responses.WaypointsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Error Querying Waypoints",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create multiple waypoints based on JSON, all must have sentinel ID of \"-1\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Waypoint"
                ],
                "summary": "Create multiple waypoints",
                "parameters": [
                    {
                        "description": "Array of Waypoint Data",
                        "name": "waypoints",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Waypoint"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/responses.WaypointsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Waypoint Data",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Error Creating Waypoint",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Designation": {
            "description": "Describes a special purpose for a Waypoint",
            "type": "string",
            "enum": [
                "launch",
                "land",
                "obstacle",
                "payload"
            ],
            "x-enum-varnames": [
                "Launch",
                "Land",
                "Obstacle",
                "Payload"
            ]
        },
        "models.Drone": {
            "description": "describes the drone being flown",
            "type": "object",
            "required": [
                "alt",
                "battery_voltage",
                "heading",
                "lat",
                "long",
                "speed",
                "timestamp",
                "v_speed"
            ],
            "properties": {
                "timestamp": {
                    "type": "integer",
                    "x-order": "1",
                    "example": 1698544781
                },
                "lat": {
                    "type": "number",
                    "x-order": "2",
                    "example": 49.267941
                },
                "long": {
                    "type": "number",
                    "x-order": "3",
                    "example": -123.24736
                },
                "alt": {
                    "type": "number",
                    "x-order": "4",
                    "example": 100
                },
                "v_speed": {
                    "type": "number",
                    "x-order": "5",
                    "example": -1.63
                },
                "speed": {
                    "type": "number",
                    "x-order": "6",
                    "example": 0.98
                },
                "heading": {
                    "type": "number",
                    "x-order": "7",
                    "example": 298.12
                },
                "battery_voltage": {
                    "description": "Payloads TBD",
                    "type": "number",
                    "x-order": "9",
                    "example": 2.6
                }
            }
        },
        "models.Waypoint": {
            "description": "describes a location in GCOM",
            "type": "object",
            "required": [
                "alt",
                "id",
                "lat",
                "long",
                "name"
            ],
            "properties": {
                "id": {
                    "description": "To create a waypoint, ID of \"-1\" must be passed",
                    "type": "string",
                    "x-order": "1",
                    "example": "1"
                },
                "name": {
                    "type": "string",
                    "x-order": "2",
                    "example": "Alpha"
                },
                "lat": {
                    "type": "number",
                    "x-order": "3",
                    "example": 49.267941
                },
                "long": {
                    "type": "number",
                    "x-order": "4",
                    "example": -123.24736
                },
                "alt": {
                    "type": "number",
                    "x-order": "5",
                    "example": 100
                },
                "radius": {
                    "description": "Radius around waypoint where it is considered flown over",
                    "type": "number",
                    "x-order": "6",
                    "example": 10
                },
                "designation": {
                    "description": "Designation of waypoint, none by default",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Designation"
                        }
                    ],
                    "x-order": "7",
                    "example": "land"
                },
                "remarks": {
                    "type": "string",
                    "x-order": "8",
                    "example": "Task 1 Landing Zone"
                }
            }
        },
        "responses.ErrorResponse": {
            "description": "JSON response for any error",
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "example": "Sample error message"
                }
            }
        },
        "responses.WaypointResponse": {
            "description": "Describes a response a single waypoint",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Sample success message"
                },
                "waypoint": {
                    "$ref": "#/definitions/models.Waypoint"
                }
            }
        },
        "responses.WaypointsResponse": {
            "description": "Describes a response with multiple waypoints",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Sample success message"
                },
                "waypoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Waypoint"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "GCOM Backend",
	Description:      "This is the backend service for UBC UAS",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
