consumes:
- application/json
definitions:
  models.Designation:
    description: Describes a special purpose for a Waypoint
    enum:
    - launch
    - land
    - obstacle
    - payload
    type: string
    x-enum-varnames:
    - Launch
    - Land
    - Obstacle
    - Payload
  models.Drone:
    description: describes the drone being flown
    properties:
      alt:
        example: 100
        type: number
        x-order: "4"
      battery_voltage:
        description: Payloads TBD
        example: 2.6
        type: number
        x-order: "9"
      heading:
        example: 298.12
        type: number
        x-order: "7"
      lat:
        example: 49.267941
        type: number
        x-order: "2"
      long:
        example: -123.24736
        type: number
        x-order: "3"
      speed:
        example: 0.98
        type: number
        x-order: "6"
      timestamp:
        example: 1698544781
        type: integer
        x-order: "1"
      v_speed:
        example: -1.63
        type: number
        x-order: "5"
    required:
    - alt
    - battery_voltage
    - heading
    - lat
    - long
    - speed
    - timestamp
    - v_speed
    type: object
  models.Waypoint:
    description: describes a location in GCOM
    properties:
      alt:
        example: 100
        type: number
        x-order: "5"
      designation:
        allOf:
        - $ref: '#/definitions/models.Designation'
        description: Designation of waypoint, none by default
        example: land
        x-order: "7"
      id:
        description: To create a waypoint, ID of "-1" must be passed
        example: "1"
        type: string
        x-order: "1"
      lat:
        example: 49.267941
        type: number
        x-order: "3"
      long:
        example: -123.24736
        type: number
        x-order: "4"
      name:
        example: Alpha
        type: string
        x-order: "2"
      radius:
        description: Radius around waypoint where it is considered flown over
        example: 10
        type: number
        x-order: "6"
      remarks:
        example: Task 1 Landing Zone
        type: string
        x-order: "8"
    required:
    - alt
    - id
    - lat
    - long
    - name
    type: object
  responses.ErrorResponse:
    description: JSON response for any error
    properties:
      data:
        type: string
      message:
        example: Sample error message
        type: string
    type: object
  responses.WaypointResponse:
    description: Describes a response a single waypoint
    properties:
      message:
        example: Sample success message
        type: string
      waypoint:
        $ref: '#/definitions/models.Waypoint'
    type: object
  responses.WaypointsResponse:
    description: Describes a response with multiple waypoints
    properties:
      message:
        example: Sample success message
        type: string
      waypoints:
        items:
          $ref: '#/definitions/models.Waypoint'
        type: array
    type: object
host: localhost:1323
info:
  contact:
    email: info@ubcuas.com
    name: UBC UAS
    url: https://ubcuas.com/
  description: This is the backend service for UBC UAS
  title: GCOM Backend
  version: "1.0"
paths:
  /status:
    get:
      description: Get the current status of the drone
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/models.Drone'
      summary: Get drone status
      tags:
      - Drone
  /status/history:
    get:
      description: Get drone status for the last 5 minutes
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            items:
              $ref: '#/definitions/models.Drone'
            type: array
      summary: Get drone status history
      tags:
      - Drone
  /waypoint:
    post:
      consumes:
      - application/json
      description: Create a singular waypoint based on JSON, must have sentinel ID
        of "-1"
      parameters:
      - description: Waypoint Data
        in: body
        name: waypoint
        required: true
        schema:
          $ref: '#/definitions/models.Waypoint'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.WaypointResponse'
        "400":
          description: Invalid JSON or Waypoint Data
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Error Creating Waypoint
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Create a waypoint
      tags:
      - Waypoint
  /waypoint/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a singular waypoint based on path param
      parameters:
      - description: Waypoint ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success (returns a blank Waypoint)
          schema:
            $ref: '#/definitions/responses.WaypointResponse'
        "404":
          description: Waypoint Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Error Deleting Waypoint
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Delete a waypoint
      tags:
      - Waypoint
    get:
      consumes:
      - application/json
      description: Get a singular waypoint based on path param
      parameters:
      - description: Waypoint ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.WaypointResponse'
        "404":
          description: Waypoint Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Error Querying Waypoint
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get a waypoint
      tags:
      - Waypoint
    patch:
      consumes:
      - application/json
      description: Edit a singular waypoint based on path param and JSON
      parameters:
      - description: Waypoint ID
        in: path
        name: id
        required: true
        type: integer
      - description: JSON fields
        example: '{"name": "Whiskey}'
        in: body
        name: fields
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.WaypointResponse'
        "400":
          description: Invalid JSON or Waypoint ID
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Waypoint Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Error Editing Waypoint
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Edit a waypoint
      tags:
      - Waypoint
  /waypoints:
    delete:
      consumes:
      - application/json
      description: Delete multiple waypoints based on json body
      parameters:
      - description: Waypoint IDs
        in: body
        name: ids
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: Success (returns a blank Waypoint)
          schema:
            $ref: '#/definitions/responses.WaypointResponse'
        "400":
          description: Invalid JSON or Waypoint IDs
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Waypoints Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Error Deleting Waypoint
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Delete multiple waypoints
      tags:
      - Waypoint
    get:
      consumes:
      - application/json
      description: Get all waypoints in the database
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.WaypointsResponse'
        "500":
          description: Internal Error Querying Waypoints
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get all waypoints
      tags:
      - Waypoint
    post:
      consumes:
      - application/json
      description: Create multiple waypoints based on JSON, all must have sentinel
        ID of "-1"
      parameters:
      - description: Array of Waypoint Data
        in: body
        name: waypoints
        required: true
        schema:
          items:
            $ref: '#/definitions/models.Waypoint'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.WaypointsResponse'
        "400":
          description: Invalid JSON or Waypoint Data
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Error Creating Waypoint
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Create multiple waypoints
      tags:
      - Waypoint
produces:
- application/json
swagger: "2.0"
